### ISSUE TITLE
Switching between monitors

### ISSUE THREAD

**Issue by reDpz** [Duckonaut/split-monitor-workspaces#100]
`split-changemonitor` doesn't change focus to a different monitor it moves the currently selected window to that monitor alongside it.

Is there an option to just switch between monitors?

**Comment by zjeffer** [comment]
@reDpz Did you mean to close this?

**Comment by reDpz** [comment]
Yeah, I realised there was a dispatcher on Hyprland called `focusmonitor` and you can pass in `+1/-1` to get what you want
