### ISSUE TITLE
Monitor disabled via hyprctl is immediately re-enabled

### ISSUE THREAD

**Issue by toamz** [Duckonaut/split-monitor-workspaces#110]
I have two monitors connected to Hyprland, one laptop internal and one HDMI external.
When I try to disable any one of the monitors using `hyprctl keyword monitor "eDP-1, disable"` command, the monitor turns off but then immediately turns back on as if nothing happened. It does not happen when this plugin is unloaded/disabled.

I tried to debug it myself and noticed that "monitorRemoved" callback is called before the monitor is actually disabled (removed from `CCompositor::m_vMonitors` vector) and thought that when the plugin tries to map the workspaces to the "to-be disabled" monitor it causes it to enable, but it turned out not to be the issue.

The actual issue is at the end of the `void mapWorkspacesToMonitors()` function, line: `HyprlandAPI::reloadConfig();`.
Because I have a laptop, I want to be able to disable and enable the internal monitor without unplugging it (for example when closing the laptop screen without suspending it), which means I permanently have it enabled in Hyprland config, and by reloading the config whenever monitor is disconnected (or disabled) it re-enables the monitor I just disabled.

Fix seems simple to me: don't reload the config.
Is there a reason we do that, since we already moved the workspaces before that directly using the `moveWorkspaceToMonitor` function?
This could possible cause more temporary hyprctl changes to be overwritten by the saved configuration.

**Comment by zjeffer** [comment]
We reload the config after writing the persistent workspace rules, so they are reapplied every time something changes to the monitor configuration:

https://github.com/Duckonaut/split-monitor-workspaces/blob/d6b4d18ed4a54d336b7fea71c2d3f476a41fbd96/src/main.cpp#L281-L282

I agree it isn't a very pretty solution, but I don't really know a better way to do this. 
Maybe there is a way to do the persistent workspace rules with temporary hyprctl commands? I'll try to look into this soon.

I could also add an option to the plugin that disables the persistent workspace rules (then I could only reload the config if it's enabled), but I'm not sure I like that solution: depending on if a user toggles this option, they would suddenly have different behaviour regarding config reloads, causing a lot of confusion...
