### ISSUE TITLE
Inactive workspaces always showing in waybar

### ISSUE THREAD

**Issue by marnas** [Duckonaut/split-monitor-workspaces#116]
After #111 all the workspaces show in waybar using "hyprland/workspaces" module all the time.

That's pretty annoying because I can't tell anymore whether I have something in a workspace or if it's empty without navigating to it.

Is this an expected behavior?

**Comment by zjeffer** [comment]
Ah, we forgot to do this: https://github.com/Duckonaut/split-monitor-workspaces/pull/111#issuecomment-2266146252

@toamz I'll take care of it

**Comment by zjeffer** [comment]
> That's pretty annoying because I can't tell anymore whether I have something in a workspace or if it's empty without navigating to it.

FYI: you can change css styles in waybar to make this clearer:

![image](https://github.com/user-attachments/assets/e972091c-61b3-4d75-b727-eff1589c193b)

Active workspace has a light grey background with a white line, non-empty workspaces have a light grey background and empty workspaces have a dark grey background. You can see this in my waybar config: https://github.com/zjeffer/dotfiles/blob/main/.config/hypr/apps/waybar/style.css

**Comment by marnas** [comment]
Thank you for the advise.

I tried to target `#workspaces button.empty` and I can modify the background-color, however if I try to set a `display: none;` which is the behavior I'm trying to replicate, waybar just crashes.

It's been a while since I played with css properly, am I missing something?

**Comment by toamz** [comment]
Waybar does not implement full CSS. It is using GTK css subset and display is not one of the supported properties, as can be seen on https://docs.gtk.org/gtk3/css-properties.html, which is linked in waybar documentation.

The linked pull request should help you though.
