### ISSUE TITLE
Failed to load plugin after computer restart

### ISSUE THREAD

**Issue by rileyhawk1417** [Duckonaut/split-monitor-workspaces#120]
Hi not sure if anyone else has experienced the plugin not being found after restarting the computer.

I installed the plugin via `hyprpm` which worked fine while I was logged in. Then after restarting the computer the plugin failed to load.
![2024-08-19T05:46:13,455662914+02:00](https://github.com/user-attachments/assets/5a8981f4-67fc-41d5-8b24-e6f1b7f9938e)

It started working again after running `hyprpm update` which was to fetch the headers. I installed hyprland through the AUR not sure if thats what's causing the plugin to act weird and not load when the session starts.

**Comment by zjeffer** [comment]
Did you update Hyprland before restarting your computer? If so, that's the reason: it needs to update the headers for the plugin to work every time you update Hyprland.

**Comment by rileyhawk1417** [comment]
I did update Hyprland before restarting the computer. In fact had updated hyprland then installed hyprpm right after.

I found a fix somewhere in the hyprland docs

> [Hyprland docs](https://wiki.hyprland.org/Plugins/Using-Plugins/#manual)
> You can add exec-once = hyprpm reload -n to your Hyprland config to have plugins loaded at startup. -n will make hyprpm send a notification if anything goes wrong (e.g. update needed)

For now thats whats working for me.

**Comment by zjeffer** [comment]
If you update Hyprland and then run hyprpm update, I think hyprpm will still see the old version because that's the version you're running. 

Any time you update Hyprland, you'll have to run hyprpm update the next boot or else none of your plugins will work. 

About the fix: that's basically how you're always supposed to use hyprpm :)
