### ISSUE TITLE
Weird behaviour with persistent workspaces disabled after reboot

### ISSUE THREAD

**Issue by marnas** [Duckonaut/split-monitor-workspaces#121]
Hey guys, I noticed that there's something off if you set `enable_persistent_workspaces = false` in your configs.

If you start from a configuration where `enable_persistent_workspaces = true` or not specified (default true), and then set it to false, the plugin will work as expected until next reboot.

However after you reboot the machine the workspaces behave as if the plugin wasn't installed, giving workspace 1 on screen one, workspace on screen 2 etc.

I'm aware of #120 however in my case other commands like `split-changemonitor` seems to work which suggest that the plugin loaded, so I'm not sure those two issues are related.

**Comment by zjeffer** [comment]
Thanks for reporting, I think I found what's going wrong, fixing...
