### ISSUE TITLE
Switching focus between monitors

### ISSUE THREAD

**Issue by crizzy9** [Duckonaut/split-monitor-workspaces#129]
I tried using this plugin but i am unable to switch between monitors
`bind = $mainMod, Tab, split-workspace`, previous only moves between workspaces in my currently selected monitor

I want to move/cycle focus between different monitors i have setup. is there a way to do that with this plugin?

**Comment by crizzy9** [comment]
Nevermind i was able to use `$mainMod, Tab, focusmonitor, +1`

**Comment by rmelendezz** [comment]
Thanks for this, I was a bit confused at first, I ended up using "split-monitor" instead
