### ISSUE TITLE
Where to set the config value?

### ISSUE THREAD

**Issue by Kazuto** [Duckonaut/split-monitor-workspaces#13]
I've tried setting it in `hyprland.conf` at `plugins` 

```
plugin {
  hyperload {
    config = "~/.config/hypr/hyprload.toml"
  },
  split-monitor-workspaces {
    count: 5,
  }
}
```

as well as in `hyprload.toml`
```
[split-monitor-workspaces]
count = 5
```

but none of these methods work

**Comment by zjeffer** [comment]
What do you mean with "doesn't work"? Does it crash? Do the keybinds not work? Does it not assign the correct window ids?

**Comment by RED-404** [comment]
I have my count set to 6
If I do a reload of hyprload "bind=SUPERSHIFT,R,hyprload,reload" it sets.
1-10 to DP-3
11-20 to DP-1
If I log-in with my second monitor DP-1 off and then turn it on, it triggers and properly sets.
1-6 DP-3
7-12 DP-1

It has only properly set itself twice with a reload.

**Comment by zjeffer** [comment]
I assume it is due to this Hyprland bug: https://github.com/hyprwm/Hyprland/issues/2510

**Comment by sanjayjaras** [comment]
That issue [issues/2510](https://github.com/hyprwm/Hyprland/issues/2510) seems resolved but config value doesn't reflect.

**Comment by Duckonaut** [comment]
Hmm, this is probably related to how Hyprland lazy-loads the config file, so the value doesn't get populated as the plugin is loaded. I'll try to force it to.
