### ISSUE TITLE
Feature Request: Shift Workspaces Right / Left 

### ISSUE THREAD

**Issue by lilboopeek** [Duckonaut/split-monitor-workspaces#133]
Hello,

I would like to request a feature for the plugin that allows users to shift their workspaces to the right or left. For example, moving everything from workspace 1 to workspace 2, workspace 2 to workspace 3, so user can have easily a new free Workspace. This would greatly enhance workspace management and organization.

Thank you for considering this feature!

Best regards,
Eskander

**Comment by zjeffer** [comment]
I like the idea, but I feel like this is something that should be implemented in Hyprland, maybe you can open an issue there? It seems kind of out of scope for this plugin.
