### ISSUE TITLE
Headers missing

### ISSUE THREAD

**Issue by vitezprchal** [Duckonaut/split-monitor-workspaces#134]
After running `hyprpm add https://github.com/Duckonaut/split-monitor-workspaces` command.
```
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Verifying headers
 
✖ Headers missing. Please run hyprpm update to fix those
```

I've seen this [issue](https://github.com/Duckonaut/split-monitor-workspaces/pull/60), however I'm unable to fix this.

**Comment by zjeffer** [comment]
Did you try `hyprpm update`, like it says in the error?

**Comment by vitezprchal** [comment]
Yes, I've tried it and after adding `hyprpm add https://github.com/hyprwm/hyprland-plugins` it seems I'm able to build it.
So far I'm enjoying this plugin however when I switch workspaces there seems to be a delay - lag? My cursor just stops for a while until the whole animation is done.

**Comment by zjeffer** [comment]
> So far I'm enjoying this plugin however when I switch workspaces there seems to be a delay - lag? My cursor just stops for a while until the whole animation is done.

Can you create a new issue for this? With more details please (which workspace do you switch to, or is it every workspace, does it also happen when you switch to the same workspace using pure hyprland commands instead of going through the plugin, etc)
