### ISSUE TITLE
hyprctl

### ISSUE THREAD

**Issue by Rdeisenroth** [Duckonaut/split-monitor-workspaces#14]
i can't use the dispatcher with hyprctl:
```sh
~ hyprctl dispatch split-workspace,1
Invalid dispatcher
```

**Comment by zjeffer** [comment]
Does it also not work when defining keybinds with bind=? Or is it just the dispatcher that doesn't work?

**Comment by zjeffer** [comment]
Just tried it myself, the correct command is: `hyprctl dispatch split-workspace 1`, without the comma.

**Comment by Rdeisenroth** [comment]
Oh yeah that works, thx
