### ISSUE TITLE
Invalid dispatcher

### ISSUE THREAD

**Issue by ProjectInfinity** [Duckonaut/split-monitor-workspaces#20]
I think I have installed hyprload correctly, the keybinds work for updating, installing, reloading etc.

I have added split-monitor-workspaces to hyprload.toml etc.

However when I go to hyprland.conf to edit the dispatchers from "workspace" to "split-workspace", hyprland complains about it being an invalid dispatcher. What could I be doing wrong?

**Comment by Duckonaut** [comment]
The plugin could be silently crashing as it's getting loaded. If that's the case, try sending me the Hyprland log from you trying to load it.

**Comment by ironveil** [comment]
I also have this issue.

Doing what @Longpiggy says doesn't fix it for me, as it says that it cannot load the plugin twice. There are no errors in the logfile either.

**Comment by zjeffer** [comment]
@ProjectInfinity @ironveil @bobblkabb Can you guys test again with the latest commit of this plugin and Hyprland, and installing it through hyprpm?

**Comment by ironveil** [comment]
> @ProjectInfinity @ironveil @bobblkabb Can you guys test again with the latest commit of this plugin and Hyprland, and installing it through hyprpm?

Just tried it in a VM and the binds actually work now, appears to have been fixed _(haven't tried with two monitors because it's just a VM)_.
