### ISSUE TITLE
Switch Between Monitors

### ISSUE THREAD

**Issue by winterSteve25** [Duckonaut/split-monitor-workspaces#25]
Not sure if this is the right place to ask... Is there a way to switch between monitors and send windows to monitors like 

```lua 
awful.screen.focus_relative(-1)
client:move_to_screen(client.screen.index - 1)
``` 
in awesomewm?

**Comment by Duckonaut** [comment]
`split-changemonitor` and `split-changemonitorsilent` (with args being one of `next`, `prev`, `+1` or `-1`) added in d8c97d60753f70d686588ad3b0a877e2ca67ff72

**Comment by winterSteve25** [comment]
Many thanks!
