### ISSUE TITLE
crash when loading.

### ISSUE THREAD

**Issue by CallMeEchoCodes** [Duckonaut/split-monitor-workspaces#3]
so i was setting up hyprload to finally autoupdate plugins and it was crashing. i gave up and switched back to just using this and it turns out the build i had been using of this repo is now somehow broken. the only thing that changed was me fixing seatd socket perms but even with logind backend its broken. i can provide any logs if needed but for some reason it doesnt coredump or really crash at all. it just exits

**Comment by Duckonaut** [comment]
Huh, that's worrying. When does it exactly fail? And please provide the hyprland crash log from `~/.hyprland` if you can. If not, try just the most recent log from `/tmp/hypr/`

**Comment by Gajus84** [comment]
Most likely not related, but after one if the three commits on May 9, 2023, Hyprland-Git breaks with the following output from the main log:

`[LOG]  [hookSystem] New hook event registered: urgent
[LOG] Hyprctl: dispatcher movewindowpixel : 0 -1404,address:0x555c7a7628d0
[CRITICAL] Hyprland has crashed :( Consult the crash report at /home/xxx/.hyprland/hyprlandCrashReport2303.txt for more information.`

The Crashreport ends with the same Hyprctl dispatch.

Stable Hyprland still works and disabling the plugin also fixes the crash on Git-Version.

**Comment by CallMeEchoCodes** [comment]
This appears to be caused by using the wrong hyprland headers. you fixed it with the checkout
