### ISSUE TITLE
Crash on b80c72c7ddbf79147d64759c8659eb5939d0327e on nixos

### ISSUE THREAD

**Issue by jacekpoz** [Duckonaut/split-monitor-workspaces#34]
unfortunately no crash report from hyprland, the only thing I have is its output and here's what that tells me:
```
[ERR] [hookSystem] Hook from plugin 15255a0 caused a SIGSEGV, queueing for unloading.
[LOG]  [PluginSystem] Plugin split-monitor-workspaces unloaded.
```
launching without the plugin works fine, with it crashes instantly

**Comment by nonetrix** [comment]
Might not be the plugin
https://github.com/hyprwm/Hyprland/issues/3993

**Comment by jacekpoz** [comment]
check the issue linked in that one (https://github.com/hyprwm/Hyprland/issues/3985), it's definitely this plugin

**Comment by nonetrix** [comment]
Attempted to use it on Nix with the recommended configuration and it just says 
```failed to load the following plugins:
/nix/store/6aylakgmzvcfvz5xsf85skpz8njf38bm-split-monitor-workspaces-0.1/lib/libsplit-monitor-workspaces.so```

Trying to do it inside of the terminal just returns
```
~
❯ hyprctl plugin load /nix/store/6aylakgmzvcfvz5xsf85skpz8njf38bm-split-monitor-workspaces-0.1/lib/libsplit-monitor-workspaces.so
error in loading plugin

~
❯
```
Is this related?

**Comment by sdooweloc** [comment]
When you say it works fine, do you mean it functions properly and everything? I just updated to the latest git for Hyprland and while I am not having any crashing I am noticing that even though the plugin is loaded, the system isnt behaving as if the plugin is loaded

@jacekpoz

**Comment by jacekpoz** [comment]
it all works properly when loading manually / rebuilding but I didn't check on the latest commit

I'll let you know my current hyprland commit and check on latest when I have time

**Comment by jacekpoz** [comment]
currently on `59cb0e20def602c0fe928c40f8398daa7ea1427d`, will check on the latest commit in 3-4 hours

**Comment by jacekpoz** [comment]
indeed, nothing changed in `d74607e414dcd16911089a6d4b6aeb661c880923`

**Comment by sdooweloc** [comment]
hmmm interesting. im on `8bd86cf37e245088433156796f1bc72542ca09ad` and it isnt playing nice. Maybe I try a nuke and repull of things. 

> indeed, nothing changed in `d74607e414dcd16911089a6d4b6aeb661c880923`

**Comment by sdooweloc** [comment]
yeah nuking the plugin path and repulling seems to have fixed things strangely. Thanks for checking lol

**Comment by sdooweloc** [comment]
> just tried that, nothing changed
> 
> are you on nixos as well or another distro?

Sorry I hadnt tried a restart of Hyprland yet to see if the error or functionality persists I was just meaning doing a nuke and re clone fixed the plugin not working at all lol

**Comment by nonetrix** [comment]
I have it working now kinda, but I'm not using the newest commit just the one NixOS ships. However, when trying to use it on the newest commit I didn't have crashes, just said it couldn't load. I have my configs uploaded on GitHub, however they are about 9 months out of date. I will date the repo to my current configs soon hopefully though

**Comment by jacekpoz** [comment]
just updated to `af6aae4e12b96fff701d8ae8fcb48ea8bb51009f`, no longer happening

if anyone still has this please comment, I'll reopen
