### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MrRoy** [Duckonaut/split-monitor-workspaces#4]
Hello,

I packaged your plugin for Gentoo, and I noticed that your plugin doesn't have a license. If would be nice to have one. The official plugins use [the BSD license](https://github.com/hyprwm/hyprland-plugins/blob/main/LICENSE)

Since I packaged your plugin in the same package as the official plugins, I used the BSD license. Let me know if tihs is incorrect and I will change it.

**Comment by Duckonaut** [comment]
Oh yeah, BSD license is the one I wanted to use here as well. Completely fine, will add it myself
