### ISSUE TITLE
split-changemonitor not executing in one direction

### ISSUE THREAD

**Issue by JangXa** [Duckonaut/split-monitor-workspaces#41]
Using the split-change monitor setup I cant send a window from middle screen to left.

I have a three screen setup:

HDMI-A-2 (ID 2) | DP-1 (ID 0)| DP-2 (ID 1)

monitors are configured as this:
```
monitor=DP-1,3440x1440@144,0x240,1,vrr,1                                          
monitor=DP-2,1920x1080@144,3440x0,1,transform,1                                  
monitor=HDMI-A-2,1920x1080@144,-1920x420,1,vrr,1 
```

Using `hyprctl dispatch split-changemonitor +1` I get the expected behavior: 
Windows cycle through `HDMI-A-2 --> DP-1 --> DP-2 --> HDMI-A-2 ...`

but with `hyprctl dispatch split-changemonitor -1` :

`<-- HDMI-A-2 <-/- DP-1 <-- DP-2`

It seems like with +1 it will correctly wrap from 2 -> 0 but with -1 it wont map from 0 to 2.

Great plugin, exactly what I need to switch from dwm to hyprland!

**Comment by zjeffer** [comment]
@JangXa Can you test whether #45 fixes your issue?
