### ISSUE TITLE
Makefile assumes Xwayland

### ISSUE THREAD

**Issue by MrRoy** [Duckonaut/split-monitor-workspaces#5]
I packaged your plugin for Gentoo, and noticed that the build fails if wlroots is built without Xwayland support:
```
~/git/split-monitor-workspaces $ g++ -shared -fPIC --no-gnu-unique $SOURCE_FILES -o $PLUGIN_NAME.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "${HYPRLAND_HEADERS}" -Iinclude -std=c++23
In file included from /home/jroy/git/Hyprland/src/managers/../defines.hpp:1,
                 from /home/jroy/git/Hyprland/src/managers/KeybindManager.hpp:3,
                 from src/main.cpp:3:
/home/jroy/git/Hyprland/src/managers/../includes.hpp:115:10: fatal error: wlr/xwayland.h: No such file or directory
  115 | #include <wlr/xwayland.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
Passing `-DNO_XWAYLAND` to the g++ command solves the problem.
For the Gentoo package, if wlroots is built without Xwayland support, I patch the makefile to add the `-DNO_XWAYLAND` parameter to g++, but it would be nice to have a cleaner solution

**Comment by Duckonaut** [comment]
That's up to Hyprland to fix. There is no way to detect if the user is running a build with `NO_XWAYLAND` defined at build time or not. Best I could do is introduce a NO_XWAYLAND flag in the makefile as well, but it'd still require that the user define it. There is talk in Hyprland of including headers *properly* instead of doing it the way its done right now, maybe after that there will be progress

**Comment by Duckonaut** [comment]
I was mistaken, actually. `hyprctl version -j` will contain the build time flags. I plan to move to a more robust solution than the makefile, will fix then.

**Comment by Duckonaut** [comment]
When reworking for the pkg-config support (upstream hyprland changes) I added this. Check if it works as of 5d13b75b8d3d54c3babb4acc85aa3d463d639923

**Comment by MrRoy** [comment]
I tested with the latest commit, and it builds fine with or without X-enabled wlroots/hyprland. Thanks!
