### ISSUE TITLE
split-monitor-workspaces is not working

### ISSUE THREAD

**Issue by Linux-DADDY** [Duckonaut/split-monitor-workspaces#73]
Hey, I have followed your guide to install it, but it is not working, it's not getting installed with not errors, I have asked this on NixOS discord forum and an user have said that it's outdated, I am not sure if it's really is or not. But i really want to use it on my machine, Thank you.

**Comment by Expressive-Synapse** [comment]
There was a recent change to Hyprland which is likely why there's an issue with the plugin.

**Comment by Duckonaut** [comment]
Yeah, looks like Hyprland moved away from C++ STL `shared_ptr` which used to be returned by the API towards a custom impl in [PR #5883](https://github.com/hyprwm/Hyprland/pull/5883). Will fix soon

**Comment by Duckonaut** [comment]
Fixed by #74
