### ISSUE TITLE
Plugin broken on the latest Hyprland

### ISSUE THREAD

**Issue by AlphaNecron** [Duckonaut/split-monitor-workspaces#84]
![image](https://github.com/Duckonaut/split-monitor-workspaces/assets/57827456/28b5f764-622c-405b-91ef-b76c10452859)
![image](https://github.com/Duckonaut/split-monitor-workspaces/assets/57827456/2c2f3cde-d38b-4e22-afeb-a078f4cd10da)
Hyprland 0.4.0 introduced some *massive* changes, perhaps that's the culprit?

**Comment by AlphaNecron** [comment]
Latest on Arch Linux, `cba1ade848feac44b2eda677503900639581c3f4` to be exact.

**Comment by zjeffer** [comment]
If you're running that commit, `hyprpm` should install the pinned version: 

https://github.com/Duckonaut/split-monitor-workspaces/blob/e3cc1a8fc7dc623adf100e63ae5a9997647f1250/hyprpm.toml#L7

How are you installing the plugin?

**Comment by AlphaNecron** [comment]
![image](https://github.com/Duckonaut/split-monitor-workspaces/assets/57827456/b9f81aa7-e1ea-4ab2-8815-37f5a1e7aebc)
Using this command, somehow installing `hyprwayland-scanner-git` and re-adding the repository did work. Thanks for that speedy support anyways.

**Comment by AlphaNecron** [comment]
It worked *flawlessly` without `hyprwayland-scanner-git` before, don't know how lol.

**Comment by zjeffer** [comment]
I'm having the same issue today, seems to be an issue on Hyprland's side:

https://github.com/hyprwm/Hyprland/issues/6115
https://github.com/hyprwm/Hyprland/issues/6139

Reinstalling hyprwayland-scanner-git doesn't work for me, though  :(

**Comment by AlphaNecron** [comment]
Tried removing the repository and force it to rebuild from scratch did the trick, check if it works for you.

**Comment by AlphaNecron** [comment]
Try removing the repository and force it to rebuild, worked for me.

**Comment by AlphaNecron** [comment]
I suspect the AUR package is outdated, try the latest build then?

**Comment by AlphaNecron** [comment]
By the way, have you done `hyprpm update` yet?

**Comment by ffernn-dev** [comment]
I'm having the same issue :(
I've got hyprwayland-scanner v0.3.8-1, and I've tried removing the plugin and adding it again

**Comment by zjeffer** [comment]
I tried everything from cleaning every hyprpm related folder, running hyprpm update, reinstalling hyprwayland-scanner(-git), etc. Nothing seems to fix it. 

Either way it's a problem in Hyprland and not this plugin.
