### ISSUE TITLE
Notifications break hyprlock

### ISSUE THREAD

**Issue by dotaxis** [Duckonaut/split-monitor-workspaces#89]
Not sure if there are logs I can post to help with this, but when my monitors wake up while hyprlock is active, the notifications seem to steal my keyboard input and I'm forced to restart my PC.

![image](https://github.com/Duckonaut/split-monitor-workspaces/assets/11805686/b3da73a2-8b86-4e7c-94d8-aaab04c9e9d6)

The enable_notifications option does not seem to be respected either. I've tried setting it to both `0` and `false` but it still pushes them to the screen.

If there's any more information I can give to help I'd be happy to.

**Comment by zjeffer** [comment]
> the notifications seem to steal my keyboard input and I'm forced to restart my PC.

This seems like a bug in Hyprland, because this plugin simply uses Hyprland's Plugin API for showing those notifications.

> The enable_notifications option does not seem to be respected either. I've tried setting it to both 0 and false but it still pushes them to the screen.

This is weird, what version of Hyprland and split-monitor-workspaces are you on?

**Comment by dotaxis** [comment]
```
$ hyprctl version
Hyprland, built from branch main at commit 1d2acbe19355c8640d54a4b6cba225c6f4370c85  (config: add absolute monitor workspace selectors (5848)).
Date: Fri May 3 11:38:00 2024
Tag: v0.39.1-138-g1d2acbe1, commits: 4598

$ hyprctl plugin list
Plugin split-monitor-workspaces by Duckonaut:
	Handle: 56b0216eef20
	Version: 1.1.0
	Description: Split monitor workspace namespaces
```
Didn't realize I was on an old version of hyprland. I am using the `-git` AUR package so not sure exactly how it's a month out of date.

I'll rebuild with the latest version and see if the issue persists.

**Comment by dotaxis** [comment]
Building hyprland from source on v0.40 seems to have fixed the `enable_notifications` flag, and I have not been able to reproduce the hyprlock issue either.

Gonna close this because I think the issue was weird version mismatching. Sorry about that.
