### ISSUE TITLE
Fails to compile under hyprland-git

### ISSUE THREAD

**Issue by DissolveDZ** [Duckonaut/split-monitor-workspaces#99]
Just started my pc and noticed that this plugin currently fails to build, i'm using hyprpm and I automatically update all plugins and noticed that some recent changes might have broken it for hyprland-git. Hope this gets fixed soon because I really like this plugin

**Comment by DissolveDZ** [comment]
the error was that i didn't have hyprutils installed but after it compiled fine, however although it compiled fine and i reloaded it etc. it started not recognizing split-workspace from the config file even though it apparently compiled fine

**Comment by zjeffer** [comment]
@DissolveDZ Can you provde your hyprland log from the point where you load the plugin with hyprpm? I assume it's maybe crashing or not launching properly if you're getting config errors.

**Comment by DissolveDZ** [comment]
the logs I found say nothing important and don't even say that hyprland crashed / failed to load something, when starting it says hyprland.conf at line 161: Invalid dispatcher, requested "split-workspace" does not exist even though prior in the config i do exec-once = hyprpm reload -n and i re-built and enabled the plugin completely

**Comment by DissolveDZ** [comment]
nvm i just did the same thing i have been doing for the last 30 minutes and it just started working again. Kind of weird but I guess I can close this, hope it's fixed for good now

**Comment by zjeffer** [comment]
Might just be hyprpm being weird. Let me know if it happens again.
